
# Set Java compatibility
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8 --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED
android.useAndroidX=true
org.gradle.java.home=/home/nicksonkipkogei/.sdkman/candidates/java/17.0.9-tem

# Android configurations
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.enableJetifier=true

# Gradle performance
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.parallel=true

# Force Java 17
org.gradle.java.installations.fromEnv=JAVA_HOME
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false

# Suppress compileSdk warning
android.suppressUnsupportedCompileSdk=35

